# Generated by Django 2.2.7 on 2019-11-08 15:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_auto_20191108_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(help_text='昵称长度4-20个字符，支持中英文、数字、-、_', max_length=128, unique=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9-_一-龥]+$', '昵称长度4-20个字符，支持中英文、数字、-、_', 'invalid')], verbose_name='昵称'),
        ),
    ]
