# Generated by Django 2.2.7 on 2019-11-09 21:54

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_auto_20191108_1650'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectgroup',
            options={'verbose_name': '项目组', 'verbose_name_plural': '项目组'},
        ),
        migrations.CreateModel(
            name='ProjectPeople',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='姓名')),
                ('attendance_group', models.CharField(max_length=128, verbose_name='考勤系统用户名')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_people', to='book.ProjectGroup', verbose_name='项目组')),
            ],
            options={
                'verbose_name': '人员表',
                'verbose_name_plural': '人员表',
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance_date', models.DateField(default=django.utils.timezone.now, verbose_name='考勤时间')),
                ('reason', models.CharField(blank=True, max_length=500, null=True, verbose_name='具体事由')),
                ('in_date', models.TimeField(verbose_name='签到时间')),
                ('back_date', models.TimeField(verbose_name='签退时间')),
                ('note', models.CharField(choices=[('M', '加班'), ('F', '考勤')], default='F', max_length=10, verbose_name='备注')),
                ('people', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_people', to='book.ProjectPeople', verbose_name='姓名')),
            ],
            options={
                'verbose_name': '考勤表',
                'verbose_name_plural': '考勤表',
            },
        ),
    ]
